
---
spring:
  profiles: default
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:localdb
    username: m11m
    password: 
  h2:
    console:
      enabled: true
  
management:
  endpoint:
    health:
      show-details: always

search-api:
  kakao:
    key: 62964ac7891e18fc1292b855dc88c379 # sample key
    url: https://dapi.kakao.com/v3/search/book
